//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Unity3DTiles.Schema
{
#pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BinaryBodyReference
    {
        /// <summary>
        /// The offset into the buffer in bytes.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("byteOffset", Required = Newtonsoft.Json.Required.Always)]
        public int ByteOffset { get; set; }

        /// <summary>
        /// The datatype of components in the property.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("componentType", Required = Newtonsoft.Json.Required.Always)]
        public ComponentType ComponentType { get; set; }

        /// <summary>
        /// Specifies if the property is a scalar or vector.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public Type Type { get; set; }
    }

    /// <summary>
    /// An object defining the reference to a section of the binary body of the batch table where the property values are stored if not defined directly in the JSON.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BTProperty
    {
       public System.Collections.Generic.Dictionary<string, object> Extensions = new System.Collections.Generic.Dictionary<string, object>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BTJson
    {
        [Newtonsoft.Json.JsonProperty("extensions", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.Dictionary<string, object> Extensions = new System.Collections.Generic.Dictionary<string, object>();


        [Newtonsoft.Json.JsonProperty("extras", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Extras Extras { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ComponentType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"BYTE")]
        BYTE = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"UNSIGNED_BYTE")]
        UNSIGNED_BYTE = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"SHORT")]
        SHORT = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"UNSIGNED_SHORT")]
        UNSIGNED_SHORT = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"INT")]
        INT = 4,


        [System.Runtime.Serialization.EnumMember(Value = @"UNSIGNED_INT")]
        UNSIGNED_INT = 5,


        [System.Runtime.Serialization.EnumMember(Value = @"FLOAT")]
        FLOAT = 6,


        [System.Runtime.Serialization.EnumMember(Value = @"DOUBLE")]
        DOUBLE = 7,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Type
    {

        [System.Runtime.Serialization.EnumMember(Value = @"SCALAR")]
        SCALAR = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"VEC2")]
        VEC2 = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"VEC3")]
        VEC3 = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"VEC4")]
        VEC4 = 3,


    }

    /// <summary>
    /// Application-specific data.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class BTExtras
    {


        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }
}